info:
  contact: {}
paths:
  /CheckClientIp:
    get:
      consumes:
        - application/json
      description: Health Check from Client Ip
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check Client Ip
      tags:
        - Common
  /push/SamplePush:
    get:
      consumes:
        - application/json
      description: push messaging
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Pushing Message
      tags:
        - Push
swagger: "2.0"
